### ISSUE TITLE
Import error "SyntaxError: Unexpected token {"

### ISSUE THREAD

**Issue by PomponExpress** [jayhaluska/isolation-forest-js#1]
Thanks for building this package. I keep running into this error, so the pkg cannot work. Please help. 

`import {IsolationForest} from 'isolation-forest';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at `internal/main/run_main_module.js:21:11``

**Comment by PomponExpress** [comment]
The above error occurred in Nodejs v11.

After I upgraded it to V12, the error changes to "SyntaxError: Cannot use import statement outside a module".

**Comment by jayhaluska** [comment]
Seems like you accidently added a character in front of the import statement ->  **`**

Just remove it: `import {IsolationForest} from 'isolation-forest';`

**Comment by PomponExpress** [comment]
> Seems like you accidently added a character in front of the import statement -> **`**
> 
> Just remove it: `import {IsolationForest} from 'isolation-forest';`
Thank you for reply.
Sorry, dear. That ' was caused by Github editor; it was not in my js file.

I tried removing all space, still got an error. Please check the snapshot. 
<img width="689" alt="snap" src="https://user-images.githubusercontent.com/38215397/66689806-45d21e00-ecd8-11e9-834d-212b5f1e6c8f.png">

**Comment by PomponExpress** [comment]
[express.js.zip](https://github.com/jayhaluska/isolation-forest-js/files/3719884/express.js.zip)
This is my js file; please test it on your computer.
Ideally, it will read the CSV and then calculate the iForest score.
Thanks.

**Comment by jayhaluska** [comment]
Hmm, weird. Import should work, also in JS. I only tested my package in TypeScript.

When I rewrite your program using `require`, it works.

``` js
const csv = require('csv-parser');
const fs = require('fs');
var testData=[];
const IFModule = require('isolation-forest');
const IsolationForest = IFModule.IsolationForest;

fs.createReadStream('if.csv')
  .pipe(csv())
  .on('data', (row) => {
    // console.log(row);
    if(row.me==""){
      row.me=0;
      console.log("00")
    }
    testData.push([row._time,row.me]);
  })
  .on('end', () => {
    console.log('CSV file successfully processed');
    var isolationForest = new IsolationForest();
	isolationForest.fit(testData) // Type ObjectArray ({}[]);
	var scores = isolationForest.scores()
	console.log(scores);
  });
```

**Comment by jayhaluska** [comment]
Closing this for now. Reopen if this did not solve problem.
