### ISSUE TITLE
[Feature Request] Score new values from trained iForest

### ISSUE THREAD

**Issue by camhart** [jayhaluska/isolation-forest-js#12]
I'd like to request a feature be added so we can score a single new `DataObject` from an existing iForest.  I believe this can be accomplished by adding a function similar to what's below.  Please note I haven't tested this--just typed it out through this ticket and essentially just modified your `scores` function.

``` index.ts
public score(x: DataObject): number {
  let pathLength: number = 0;
  for(let j = 0; j < this.numberOfTrees; j++) {
    pathLength += this.trees[j].pathLength(x, this.trees[j].getRootNode(), 0)
  }
  const meanPathLength = pathLength / this.numberOfTrees;
  const score = Math.pow(2, -(meanPathLength / averagePathLength(this.subsamplingSize)));
  return score;
}
```

The `scores` function could be refactored to call `score` if you'd like.  If it's helpful I'd be happy to put a PR up.

Thanks for this library!  Extremely helpful and easy to use.

**Comment by camhart** [comment]
Just realized there's already a PR up that adds this functionality.  See https://github.com/jayhaluska/isolation-forest-js/pull/6.

Any chance we could get that reviewed, merged, and a new version released?

**Comment by jayhaluska** [comment]
Hey,
thanks for the suggestion. I did not have much time for this project recently. I'll look into the PR on the weekend and if possible merge and release a new version.

**Comment by jayhaluska** [comment]
I reviewed  #6 and there is one minor change to be made.

If it is urgent, feel free to create your own PR based on the changes of ArnaudParad together with my change suggestion.

**Comment by jayhaluska** [comment]
I just merged the PR. I will now publish a new version on NPM also.
